#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python << END

import socket
import time
import argparse


# Get arguments
service_name = "Cassandra"
port = 9042
ip = "cassandra"
timeout = 3

# Infinite loop
while True:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    result = sock.connect_ex((ip, port))
    if result == 0:
        print("{0} port is now available.".format(service_name))
        break
    else:
        print("{0} port is not open. Will check again in 3 seconds...".format(service_name))
        time.sleep(timeout)
END
>&2 echo 'Running start script...'

exec "$@"

# if [ -z "${POSTGRES_USER}" ]; then
#     base_postgres_image_default_user='postgres'
#     export POSTGRES_USER="${base_postgres_image_default_user}"
# fi
# export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# python << END
# import sys
# import time

# import psycopg2

# suggest_unrecoverable_after = 30
# start = time.time()

# while True:
#     try:
#         psycopg2.connect(
#             dbname="${POSTGRES_DB}",
#             user="${POSTGRES_USER}",
#             password="${POSTGRES_PASSWORD}",
#             host="${POSTGRES_HOST}",
#             port="${POSTGRES_PORT}",
#         )
#         break
#     except psycopg2.OperationalError as error:
#         sys.stderr.write("Waiting for PostgreSQL to become available...\n")

#         if time.time() - start > suggest_unrecoverable_after:
#             sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

#     time.sleep(1)
# END

# >&2 echo 'PostgreSQL is available'

# exec "$@"
